import javax.swing.JOptionPane;
import java.util.List;
import com.opencsv.CSVWriter;
import java.io.FileWriter;
import java.io.IOException;



public class AddEmployee extends javax.swing.JFrame {

    public AddEmployee() {
        initComponents();
    
    // Ask the handler for the next available ID
    int nextId = EmployeeFileHandler.generateNextEmpNum();
    jTxtEmpNum.setText(String.valueOf(nextId));

    // Keep it non-editable so users can't break the ID sequence
    jTxtEmpNum.setEditable(false);
    jTxtEmpNum.setFocusable(false);
    jTxtEmpNum.setBackground(java.awt.Color.LIGHT_GRAY);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextPAGIBIG = new javax.swing.JTextField();
        jLabelAddEmp = new javax.swing.JLabel();
        jTextPHILHEALTH = new javax.swing.JTextField();
        jLblEmpNum = new javax.swing.JLabel();
        jTextTIN = new javax.swing.JTextField();
        jLblLastName = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jLblFirstName = new javax.swing.JLabel();
        jLblPhoneNumber = new javax.swing.JLabel();
        jLblStatus = new javax.swing.JLabel();
        jLblPosition = new javax.swing.JLabel();
        jTxtEmpNum = new javax.swing.JTextField();
        jTxtLastName = new javax.swing.JTextField();
        jTxtFirstName = new javax.swing.JTextField();
        jTxtPhoneNumber = new javax.swing.JTextField();
        jTxtStatus = new javax.swing.JTextField();
        jTxtPosition = new javax.swing.JTextField();
        jLblSSS = new javax.swing.JLabel();
        jLblPAGIBIG = new javax.swing.JLabel();
        jLblPHILHEALTH = new javax.swing.JLabel();
        jLblTIN = new javax.swing.JLabel();
        jTextSSS = new javax.swing.JTextField();
        jLblPersonal = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextPAGIBIG, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 323, 211, -1));

        jLabelAddEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAddEmp.setText("Add New Employee");
        jPanel1.add(jLabelAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, 210, -1));
        jPanel1.add(jTextPHILHEALTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 353, 211, -1));

        jLblEmpNum.setText("Employee Number:");
        jPanel1.add(jLblEmpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 107, 140, -1));
        jPanel1.add(jTextTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 383, 212, -1));

        jLblLastName.setText("Last Name:");
        jPanel1.add(jLblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 137, 132, -1));

        jButtonSubmit.setBackground(new java.awt.Color(14, 49, 113));
        jButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubmit.setText("Submit");
        jButtonSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 90, -1));

        jLblFirstName.setText("First Name:");
        jPanel1.add(jLblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 164, 132, -1));

        jLblPhoneNumber.setText("Phone Number:");
        jPanel1.add(jLblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 194, 132, -1));

        jLblStatus.setText("Status:");
        jPanel1.add(jLblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 230, 132, -1));

        jLblPosition.setText("Position:");
        jPanel1.add(jLblPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 260, 132, -1));

        jTxtEmpNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmpNumActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtEmpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 104, 211, -1));
        jPanel1.add(jTxtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 134, 211, -1));
        jPanel1.add(jTxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 164, 211, -1));
        jPanel1.add(jTxtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 194, 211, -1));
        jPanel1.add(jTxtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 227, 211, -1));
        jPanel1.add(jTxtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 257, 211, -1));

        jLblSSS.setText("SSS");
        jPanel1.add(jLblSSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 296, 132, -1));

        jLblPAGIBIG.setText("PAGIBIG");
        jPanel1.add(jLblPAGIBIG, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 326, 132, -1));

        jLblPHILHEALTH.setText("PHILEALTH");
        jPanel1.add(jLblPHILHEALTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 353, 132, -1));

        jLblTIN.setText("TIN");
        jPanel1.add(jLblTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 386, 132, -1));

        jTextSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSSSActionPerformed(evt);
            }
        });
        jPanel1.add(jTextSSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 293, 211, -1));

        jLblPersonal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLblPersonal.setText("Personal Information");
        jPanel1.add(jLblPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 71, 170, -1));

        jButtonCancel.setBackground(new java.awt.Color(153, 0, 0));
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Close");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 90, -1));

        jPanel2.setBackground(new java.awt.Color(14, 49, 113));
        jPanel2.setAutoscrolls(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Photo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        textLogo.setFont(new java.awt.Font("Kinetika Bold", 0, 55)); // NOI18N
        textLogo.setForeground(new java.awt.Color(255, 255, 255));
        textLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLogo.setText("MotorPH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(textLogo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(textLogo)
                .addGap(21, 21, 21))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("CP2 H1102 SY24-25 Team Petix - C.Oreta, S.Singh, R.Sisles, J.Singh, D.Sumatra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtEmpNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmpNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmpNumActionPerformed

    private void jTextSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSSSActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        try {
        // Create the Employee object using the names currently in your AddEmployee.txt
        Employee newEmp = new Employee(
            Integer.parseInt(jTxtEmpNum.getText()), 
            jTxtLastName.getText().trim(),
            jTxtFirstName.getText().trim(),
            jTxtPhoneNumber.getText().trim(),
            "Regular", // Temporarily hardcoded because jComboStatus was missing
            jTxtPosition.getText().trim(),
            "N/A",     // Temporarily hardcoded because jTxtSupervisor was missing
            "N/A",     // Temporarily hardcoded because jTxtAddress was missing
            jTextSSS.getText().trim(),
            jTextPHILHEALTH.getText().trim(),
            jTextTIN.getText().trim(),
            jTextPAGIBIG.getText().trim(),
            0.0, // Basic Salary (Update this name if you find it in Design view)
            0.0, // Rice Subsidy
            0.0, // Phone Allowance
            0.0, // Clothing Allowance
            0.0, // Gross Semi-monthly
            0.0, // Hourly Rate
            0.0, // Withholding Tax
            "01/01/1990" // Birthday
        );

        EmployeeFileHandler.addEmployee(newEmp);

        JOptionPane.showMessageDialog(this, "Employee Added Successfully!");
        
        if (EmployeeTable.getInstance() != null) {
            EmployeeTable.getInstance().loadEmployeeData();
        }
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    dispose(); 
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAddEmp;
    private javax.swing.JLabel jLblEmpNum;
    private javax.swing.JLabel jLblFirstName;
    private javax.swing.JLabel jLblLastName;
    private javax.swing.JLabel jLblPAGIBIG;
    private javax.swing.JLabel jLblPHILHEALTH;
    private javax.swing.JLabel jLblPersonal;
    private javax.swing.JLabel jLblPhoneNumber;
    private javax.swing.JLabel jLblPosition;
    private javax.swing.JLabel jLblSSS;
    private javax.swing.JLabel jLblStatus;
    private javax.swing.JLabel jLblTIN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextPAGIBIG;
    private javax.swing.JTextField jTextPHILHEALTH;
    private javax.swing.JTextField jTextSSS;
    private javax.swing.JTextField jTextTIN;
    private javax.swing.JTextField jTxtEmpNum;
    private javax.swing.JTextField jTxtFirstName;
    private javax.swing.JTextField jTxtLastName;
    private javax.swing.JTextField jTxtPhoneNumber;
    private javax.swing.JTextField jTxtPosition;
    private javax.swing.JTextField jTxtStatus;
    private javax.swing.JLabel textLogo;
    // End of variables declaration//GEN-END:variables
}
