import javax.swing.JOptionPane;
import java.util.List;
import com.opencsv.CSVReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

/**
 * `AddEmployee` class provides a GUI for adding new employee records.
 * Ensures that Employee Numbers auto-increment and prevents manual edits.
 */
public class AddEmployee extends javax.swing.JFrame {

    private EmployeeTable parentTable;
    
    /**
     * Constructor - Initializes the AddEmployee form.
     * Automatically generates the next Employee Number and disables manual editing.
     */
    
    public AddEmployee(EmployeeTable parentTable) {
        this(); // Call the default constructor
        this.parentTable = parentTable; // Remember the table that opened this form
    }
    
    public AddEmployee() {
        initComponents(); // Initialize UI components
        generateNextEmpNum(); // Auto-set Employee Number
        populateAccessCombo();
        populateSupervisorCombo();

        // Prevent manual entry in Employee Number field
        jTxtEmpNum.setEditable(false);
        jTxtEmpNum.setFocusable(false);
        jTxtEmpNum.setBackground(java.awt.Color.LIGHT_GRAY);
    }
    
    private void populateAccessCombo() {
        jComboAccess.removeAllItems();
        jComboAccess.addItem("Employee");
        jComboAccess.addItem("Supervisor");
        jComboAccess.addItem("HR");
        jComboAccess.addItem("IT");
    }

    private void populateSupervisorCombo() {
        jComboSupervisor.removeAllItems();
        jComboSupervisor.addItem("N/A"); // Default option

        try (CSVReader reader = new CSVReader(new FileReader("src/data/MotorPHlogin.csv"))) {
            List<String[]> records = reader.readAll();

            for (int i = 1; i < records.size(); i++) { // Skip header
                String[] row = records.get(i);
                String access = row[3].trim(); // Access column (e.g., Supervisor)
                String firstName = row[2].trim();
                String lastName = row[1].trim();

                if (access.equalsIgnoreCase("Supervisor")) {
                    String fullName = firstName + " " + lastName;
                    jComboSupervisor.addItem(fullName);
                }
            }
        } catch (IOException | com.opencsv.exceptions.CsvException e) {
            e.printStackTrace();
        }
    }

    /**
     * Generates the next available Employee Number automatically.
     * Uses `EmployeeFileHandler` to retrieve existing employee records.
     */
    private void generateNextEmpNum() {
    List<Employee> employees = EmployeeFileHandler.loadEmployees(); // Load latest employee data

    // Find the next available Employee Number
    int newEmpNum = employees.isEmpty() ? 10001 : employees.stream()
                           .mapToInt(Employee::getEmployeeNumber)
                           .max().orElse(10000) + 1;

    jTxtEmpNum.setText(String.valueOf(newEmpNum));
    jTxtEmpNum.setEditable(false);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextPAGIBIG = new javax.swing.JTextField();
        jLabelAddEmp = new javax.swing.JLabel();
        jTextPHILHEALTH = new javax.swing.JTextField();
        jLblEmpNum = new javax.swing.JLabel();
        jTextTIN = new javax.swing.JTextField();
        jLblLastName = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jLblFirstName = new javax.swing.JLabel();
        jLblPhoneNumber = new javax.swing.JLabel();
        jLblStatus = new javax.swing.JLabel();
        jLblPosition = new javax.swing.JLabel();
        jTxtLastName = new javax.swing.JTextField();
        jTxtFirstName = new javax.swing.JTextField();
        jTxtPhoneNumber = new javax.swing.JTextField();
        jTxtStatus = new javax.swing.JTextField();
        jTxtPosition = new javax.swing.JTextField();
        jLblSSS = new javax.swing.JLabel();
        jLblPAGIBIG = new javax.swing.JLabel();
        jLblPHILHEALTH = new javax.swing.JLabel();
        jLblTIN = new javax.swing.JLabel();
        jTextSSS = new javax.swing.JTextField();
        jLblPersonal = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jComboSupervisor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboAccess = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtEmpNum = new javax.swing.JTextField();
        jTxtBirthday = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextPAGIBIG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 211, 20));

        jLabelAddEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAddEmp.setText("Add New Employee");
        jPanel1.add(jLabelAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));
        jPanel1.add(jTextPHILHEALTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 211, 20));

        jLblEmpNum.setText("Employee Number:");
        jPanel1.add(jLblEmpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 20));
        jPanel1.add(jTextTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 212, 20));

        jLblLastName.setText("Last Name:");
        jPanel1.add(jLblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 132, 20));

        jButtonSubmit.setBackground(new java.awt.Color(14, 49, 113));
        jButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubmit.setText("Submit");
        jButtonSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 90, -1));

        jLblFirstName.setText("First Name:");
        jPanel1.add(jLblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 132, 20));

        jLblPhoneNumber.setText("Phone Number:");
        jPanel1.add(jLblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 132, 20));

        jLblStatus.setText("Status:");
        jPanel1.add(jLblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 132, 20));

        jLblPosition.setText("Position:");
        jPanel1.add(jLblPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 132, 20));
        jPanel1.add(jTxtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 211, 20));
        jPanel1.add(jTxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 211, 20));
        jPanel1.add(jTxtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 211, 20));
        jPanel1.add(jTxtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 211, 20));
        jPanel1.add(jTxtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 211, 20));

        jLblSSS.setText("SSS");
        jPanel1.add(jLblSSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 132, 20));

        jLblPAGIBIG.setText("PAGIBIG");
        jPanel1.add(jLblPAGIBIG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 132, 20));

        jLblPHILHEALTH.setText("PHILEALTH");
        jPanel1.add(jLblPHILHEALTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 132, 20));

        jLblTIN.setText("TIN");
        jPanel1.add(jLblTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 132, 20));

        jTextSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSSSActionPerformed(evt);
            }
        });
        jPanel1.add(jTextSSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 211, 20));

        jLblPersonal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLblPersonal.setText("Personal Information");
        jPanel1.add(jLblPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, -1));

        jButtonCancel.setBackground(new java.awt.Color(153, 0, 0));
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Close");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 90, -1));

        jComboSupervisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 210, 20));

        jLabel1.setText("Birthday:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 20));

        jComboAccess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboAccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 210, 20));

        jLabel3.setText("Access:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, 20));

        jLabel4.setText("Supervisor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 130, 20));

        jTxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 211, 20));

        jLabel5.setText("Address:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, 20));

        jTxtEmpNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmpNumActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtEmpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 211, 20));

        jTxtBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBirthdayActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 211, 20));

        jPanel2.setBackground(new java.awt.Color(14, 49, 113));
        jPanel2.setAutoscrolls(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Photo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        textLogo.setFont(new java.awt.Font("Kinetika Bold", 0, 55)); // NOI18N
        textLogo.setForeground(new java.awt.Color(255, 255, 255));
        textLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLogo.setText("MotorPH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(textLogo)
                .addContainerGap(348, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(textLogo)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtEmpNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmpNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmpNumActionPerformed

    private void jTextSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSSSActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        try {
        // Retrieve entered data, ensuring required fields are valid
        int empNum = Integer.parseInt(jTxtEmpNum.getText().trim());
        String lastName = jTxtLastName.getText().trim();
        String firstName = jTxtFirstName.getText().trim();
        String phoneNumber = jTxtPhoneNumber.getText().trim();
        String status = jTxtStatus.getText().trim().isEmpty() ? "NA" : jTxtStatus.getText().trim();
        String position = jTxtPosition.getText().trim().isEmpty() ? "NA" : jTxtPosition.getText().trim();
        String supervisor = jComboSupervisor.getSelectedItem().toString().trim();
        String access = jComboAccess.getSelectedItem().toString().trim();
        String address = jTxtAddress.getText().trim().isEmpty() ? "NA" : jTxtAddress.getText().trim();
        String birthday = jTxtBirthday.getText().trim().isEmpty() ? "NA" : jTxtBirthday.getText().trim();

        // Convert SSS, PAGIBIG, PHILHEALTH, TIN to integers, handling empty fields
        int sssNumber = jTextSSS.getText().trim().isEmpty() ? 0 : Integer.parseInt(jTextSSS.getText().trim());
        int philHealthNumber = jTextPHILHEALTH.getText().trim().isEmpty() ? 0 : Integer.parseInt(jTextPHILHEALTH.getText().trim());
        int tinNumber = jTextTIN.getText().trim().isEmpty() ? 0 : Integer.parseInt(jTextTIN.getText().trim());
        int pagIbigNumber = jTextPAGIBIG.getText().trim().isEmpty() ? 0 : Integer.parseInt(jTextPAGIBIG.getText().trim());

        // Ensure required fields are not empty
        if (lastName.isEmpty() || firstName.isEmpty() || phoneNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Last Name, First Name, and Phone Number are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Default placeholders for missing financial data
        double basicSalary = 0.0;
        double riceSubsidy = 0.0;
        double phoneAllowance = 0.0;
        double clothingAllowance = 0.0;
        double grossSemiMonthlyRate = 0.0;
        double hourlyRate = 0.0;
        double withholdingTax = 0.0;

        // Create Employee object with corrected integer ID fields
        Employee newEmployee = new Employee(empNum, lastName, firstName, phoneNumber, status, position, supervisor,
    address, String.valueOf(sssNumber), String.valueOf(philHealthNumber), 
    String.valueOf(tinNumber), String.valueOf(pagIbigNumber), 
    basicSalary, riceSubsidy, phoneAllowance, clothingAllowance, 
    grossSemiMonthlyRate, hourlyRate, withholdingTax, birthday); // Birthday MUST be last


;


        // Save employee record via EmployeeFileHandler
        EmployeeFileHandler.saveEmployee(newEmployee);
        EmployeeFileHandler.appendToLoginCSV(empNum, lastName, firstName, access, position, supervisor);

        JOptionPane.showMessageDialog(this, "Employee added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Refresh Employee Number for next entry
        generateNextEmpNum();

        // Refresh the table view to reflect new entries
        if (parentTable != null) {
            parentTable.refreshEmployeeTable();
        }
        
        // Close the form after successful submission
        dispose();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: Invalid input! Ensure numeric values are entered correctly.", "Input Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    dispose(); 
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTxtBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBirthdayActionPerformed

    private void jTxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboAccess;
    private javax.swing.JComboBox<String> jComboSupervisor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAddEmp;
    private javax.swing.JLabel jLblEmpNum;
    private javax.swing.JLabel jLblFirstName;
    private javax.swing.JLabel jLblLastName;
    private javax.swing.JLabel jLblPAGIBIG;
    private javax.swing.JLabel jLblPHILHEALTH;
    private javax.swing.JLabel jLblPersonal;
    private javax.swing.JLabel jLblPhoneNumber;
    private javax.swing.JLabel jLblPosition;
    private javax.swing.JLabel jLblSSS;
    private javax.swing.JLabel jLblStatus;
    private javax.swing.JLabel jLblTIN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextPAGIBIG;
    private javax.swing.JTextField jTextPHILHEALTH;
    private javax.swing.JTextField jTextSSS;
    private javax.swing.JTextField jTextTIN;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtBirthday;
    private javax.swing.JTextField jTxtEmpNum;
    private javax.swing.JTextField jTxtFirstName;
    private javax.swing.JTextField jTxtLastName;
    private javax.swing.JTextField jTxtPhoneNumber;
    private javax.swing.JTextField jTxtPosition;
    private javax.swing.JTextField jTxtStatus;
    private javax.swing.JLabel textLogo;
    // End of variables declaration//GEN-END:variables
}