import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;



public class Attendance extends JFrame {
    private String empNo;  
    private User loggedInUser;
    private boolean tableEditable = false;
    private List<String[]> originalTableData = new ArrayList<>();

    public Attendance(String empNo) {
        this.empNo = empNo;
        initComponents();
        loadEmployeeName(); // ✅ Load employee name
        employeeIDLabel.setText("Employee ID: " + empNo);
        loadAttendanceRecords(empNo, LocalDate.now().minusMonths(1), LocalDate.now()); // ✅ Load last month's records
    }

    public Attendance() {
        initComponents();
    }
    
    public Attendance(int empNum, User user) {
        this(String.valueOf(empNum));
        this.loggedInUser = user;
        applyUpdateButtonRules(); // Role-based visibility
    }

    // ✅ Fetch and Display Employee Name in jLabel3
    private void loadEmployeeName() {
        String employeeName = getEmployeeName(empNo);
        jLabel3.setText("Employee Name: " + employeeName); // ✅ Set name in GUI
    } 

    // ✅ Retrieve Employee Name from Data Source
    private String getEmployeeName(String empNo) {
        return EmployeeFileHandler.getEmployee(Integer.parseInt(empNo))
                .map(e -> e.getFirstName() + " " + e.getLastName())
                .orElse("Unknown Employee"); // ✅ Handles invalid employee number
    }

    // ✅ Load Attendance Records into Table
    public void loadAttendanceRecords(String empNo, LocalDate startDate, LocalDate endDate) {
    DefaultTableModel model = (DefaultTableModel) jTableAttendance.getModel();
    model.setRowCount(0); // ✅ Clear previous data before loading new records

    List<String[]> records = AttendanceFileHandler.getAttendanceRecords(empNo, startDate, endDate);

    if (!records.isEmpty()) {
        employeeIDLabel.setText("Employee ID: " + empNo); // ✅ Dynamically updates Employee ID in GUI
    }

    for (String[] row : records) {
        model.addRow(new Object[]{row[0], row[1], row[2]});
    }

}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAttendance = new javax.swing.JTable();
        jLblEmpAtt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        startDateLabel = new com.toedter.calendar.JDateChooser();
        endDateLabel = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checkAttendanceButton = new javax.swing.JButton();
        employeeIDLabel = new javax.swing.JLabel();
        updateAttendanceButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(14, 49, 113));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time IN", "Time OUT", "Late", "Overtime", "Undertime"
            }
        ));
        jScrollPane1.setViewportView(jTableAttendance);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 161, 753, 422));

        jLblEmpAtt.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLblEmpAtt.setForeground(new java.awt.Color(255, 255, 255));
        jLblEmpAtt.setText("Employee Attendance");
        jPanel1.add(jLblEmpAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 20, 416, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Date Range:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 64, 195, -1));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 601, 85, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name : Garcia, Manuel III");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 87, 416, -1));
        jPanel1.add(startDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 87, 126, -1));
        jPanel1.add(endDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 87, 126, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("From");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 93, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 93, -1, -1));

        checkAttendanceButton.setBackground(new java.awt.Color(0, 102, 102));
        checkAttendanceButton.setForeground(new java.awt.Color(255, 255, 255));
        checkAttendanceButton.setText("Check Attendance");
        checkAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAttendanceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(checkAttendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 140, -1));

        employeeIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        employeeIDLabel.setText("Employee ID: ");
        jPanel1.add(employeeIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 115, 324, -1));

        updateAttendanceButton.setBackground(new java.awt.Color(0, 102, 102));
        updateAttendanceButton.setForeground(new java.awt.Color(255, 255, 255));
        updateAttendanceButton.setText("Update Attendance");
        updateAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAttendanceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateAttendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose ();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAttendanceButtonActionPerformed
                                                   
    if (startDateLabel.getDate() != null && endDateLabel.getDate() != null) {
        LocalDate startDate = startDateLabel.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        LocalDate endDate = endDateLabel.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

        loadAttendanceRecords(empNo, startDate, endDate);

        DefaultTableModel model = (DefaultTableModel) jTableAttendance.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            String dateStr = (String) model.getValueAt(row, 0); 

            if (dateStr != null && !dateStr.trim().isEmpty()) {
                Map<String, Double> attendanceMinutes = AttendanceFileHandler.computeDailyAttendanceMinutes(Integer.parseInt(empNo), dateStr);
                
                model.setValueAt(attendanceMinutes.get("Late"), row, 3); // ✅ Updates Late column
                model.setValueAt(attendanceMinutes.get("Overtime"), row, 4); // ✅ Updates Overtime column
                model.setValueAt(attendanceMinutes.get("Undertime"), row, 5); // ✅ Updates Undertime column
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select both start and end dates.", "Date Range Required", JOptionPane.WARNING_MESSAGE);
    }


    }//GEN-LAST:event_checkAttendanceButtonActionPerformed

    private void updateAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAttendanceButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableAttendance.getModel();

        if (!tableEditable) {
            // Save original Time IN and Time OUT values
            originalTableData.clear();
            for (int row = 0; row < model.getRowCount(); row++) {
                originalTableData.add(new String[]{
                    model.getValueAt(row, 0).toString(), // Date
                    model.getValueAt(row, 1).toString(), // Time IN
                    model.getValueAt(row, 2).toString()  // Time OUT
                });
            }

            // Enable editing only for Time IN and Time OUT
            jTableAttendance.setDefaultEditor(Object.class, new javax.swing.DefaultCellEditor(new javax.swing.JTextField()) {
                @Override
                public boolean isCellEditable(java.util.EventObject e) {
                    int col = jTableAttendance.getSelectedColumn();
                    return col == 1 || col == 2; // Allow only columns 1 & 2
                }
            });

            tableEditable = true;
            JOptionPane.showMessageDialog(this, "The table is now editable.");
        } else {
            boolean hasChanges = false;
            for (int row = 0; row < model.getRowCount(); row++) {
                String newIn = model.getValueAt(row, 1).toString().trim();
                String newOut = model.getValueAt(row, 2).toString().trim();
                String[] original = originalTableData.get(row);

                if (!newIn.equals(original[1]) || !newOut.equals(original[2])) {
                    hasChanges = true;
                    break;
                }
            }

            if (!hasChanges) {
                JOptionPane.showMessageDialog(this, "No changes were made.");
                tableEditable = false;
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to save your changes?",
                    "Confirm Save", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                saveAttendanceChanges();
                JOptionPane.showMessageDialog(this, "Changes saved successfully.");
                checkAttendanceButton.doClick(); // Refresh display
            }

            tableEditable = false;
        }
    }//GEN-LAST:event_updateAttendanceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance().setVisible(true);
            }
        });
    }

    private void applyUpdateButtonRules() {
        if (loggedInUser == null || empNo == null) {
            updateAttendanceButton.setVisible(false);
            return;
        }

        String role = loggedInUser.getAccess(); // IT, HR, Supervisor, Employee
        String viewerEmpNo = loggedInUser.getEmployeeNumber(); // who is logged in
        boolean isViewingOwn = viewerEmpNo.equals(empNo);

        switch (role) {
            case "IT":
                updateAttendanceButton.setVisible(true);
                break;
            case "HR":
            case "Employee":
                updateAttendanceButton.setVisible(false);
                break;
            case "Supervisor":
                if (!isViewingOwn && isSubordinate(viewerEmpNo, empNo)) {
                    updateAttendanceButton.setVisible(true);
                } else {
                    updateAttendanceButton.setVisible(false);
                }
                break;
            default:
                updateAttendanceButton.setVisible(false);
        }
    }
    
    private boolean isSubordinate(String supervisorEmpNo, String targetEmpNo) {
        List<Employee> allEmployees = EmployeeFileHandler.loadEmployees();
        for (Employee emp : allEmployees) {
            if (String.valueOf(emp.getEmployeeNumber()).equals(targetEmpNo)
                && emp.getImmediateSupervisor().equalsIgnoreCase(supervisorEmpNo)) {
                return true;
            }
        }
        return false;
    }
    
    private void saveAttendanceChanges() {
        List<String[]> allRecords = AttendanceFileHandler.getRawCSV();
        DefaultTableModel model = (DefaultTableModel) jTableAttendance.getModel();
        java.time.format.DateTimeFormatter dateFmt = java.time.format.DateTimeFormatter.ofPattern("MM/dd/yyyy");

        for (int row = 0; row < model.getRowCount(); row++) {
            String date = model.getValueAt(row, 0).toString().trim();
            String timeIn = model.getValueAt(row, 1).toString().trim();
            String timeOut = model.getValueAt(row, 2).toString().trim();

            for (String[] csvRow : allRecords) {
                if (csvRow[0].equals(empNo) && csvRow[3].equals(date)) {
                    csvRow[4] = timeIn;
                    csvRow[5] = timeOut;
                    break;
                }
            }
        }

        AttendanceFileHandler.overwriteCSV(allRecords);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checkAttendanceButton;
    private javax.swing.JLabel employeeIDLabel;
    private com.toedter.calendar.JDateChooser endDateLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblEmpAtt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAttendance;
    private com.toedter.calendar.JDateChooser startDateLabel;
    private javax.swing.JButton updateAttendanceButton;
    // End of variables declaration//GEN-END:variables

}