/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *login page user name and password
 */

import com.opencsv.CSVReader;         // Added for OpenCSV functionality
import com.opencsv.exceptions.CsvException; // Added for OpenCSV exceptions

import java.io.FileReader;           // Only FileReader is needed, no BufferedReader
import java.io.IOException;          // Keep for general I/O errors
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

   
public class LoginScreen1 extends javax.swing.JFrame {
    
    // login / profile lookup maps
private Map<String, String> userCredentials   = new HashMap<>();
private Map<String, String> userFullNames     = new HashMap<>();
private Map<String, User>   userMap           = new HashMap<>();

// reset‐password maps (you already have these)
private Map<String, String> securityAnswers = new HashMap<>();
private Map<String, String> userPasswordByEmpNum = new HashMap<>();
private Map<String, String> usernameByEmpNum = new HashMap<>();


    public LoginScreen1() {
        initComponents();
        getRootPane().setDefaultButton(jButtonLogin);
        loadCredentialsFromCSV("src/data/MotorPHlogin.csv"); // Path to CSV
        // Highlight 1: Center the login screen on the monitor when instantiated
        this.setLocationRelativeTo(null);
    }

    private void loadCredentialsFromCSV(String filename) {
    try (CSVReader csvReader = new CSVReader(new FileReader(filename))) {
        csvReader.readNext(); // Skip header row

        String[] values;
        while ((values = csvReader.readNext()) != null) {
            if (values.length >= 9) {
                String empNum = values[0].trim();
                String lastName = values[1].trim();
                String firstName = values[2].trim();
                String access = values[3].trim();
                String position = values[4].trim();
                String username = values[6].trim();  // From CSV
                String password = values[7].trim();  // From CSV
                String securityAnswer = values[8].trim().toLowerCase(); // For reset password

                String fullName = firstName + " " + lastName;

                userCredentials.put(username, password);
                userFullNames.put(username, fullName);

                User user = new User(empNum, fullName, access, position);
                userMap.put(empNum, user); // Map by employee number

                // Store security answer with EmpNum as key
                securityAnswers.put(empNum, securityAnswer);
                userPasswordByEmpNum.put(empNum, password);
                usernameByEmpNum.put(empNum, username);
            }
        }
    } catch (IOException | CsvException e) {
        JOptionPane.showMessageDialog(this, "Error loading credentials: " + e.getMessage());
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textLogo = new javax.swing.JLabel();
        loginLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelLogin2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(14, 49, 113));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textLogo.setFont(new java.awt.Font("Kinetika Bold", 0, 55)); // NOI18N
        textLogo.setForeground(new java.awt.Color(255, 255, 255));
        textLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLogo.setText("MotorPH");
        jPanel1.add(textLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 492, -1, -1));

        loginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginLogo.png"))); // NOI18N
        jPanel1.add(loginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 137, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 602));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 282, 201, -1));

        jLabelUsername.setText("Username:");
        jPanel2.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 285, 100, -1));

        jLabelPassword.setText("Password:");
        jPanel2.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 327, 100, -1));

        jButtonLogin.setBackground(new java.awt.Color(14, 49, 113));
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 120, 32));

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 324, 201, -1));

        jLabelLogin2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelLogin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin2.setText("Employee Login");
        jPanel2.add(jLabelLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 148, -1, -1));

        jButton1.setBackground(new java.awt.Color(14, 49, 113));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset Password ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 0, 590, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String username = jTextFieldUsername.getText().trim();
        String passwordInput = new String(jPasswordField.getPassword()).trim();


        if (userCredentials.containsKey(username) && userCredentials.get(username).equals(passwordInput)) {
            String fullName = getFullNameFromUsername(username);
            JOptionPane.showMessageDialog(this, "Login Successful!");

            // Open MainMenu screen
            String empNum = null;
for (Map.Entry<String, String> entry : usernameByEmpNum.entrySet()) {
    if (entry.getValue().equals(username)) {
        empNum = entry.getKey();
        break;
    }
}
User user = userMap.get(empNum);
            MainMenu main = new MainMenu(user);
            main.setVisible(true);
            main.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            jTextFieldUsername.setText("");
            jPasswordField.setText("");
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        jButtonLogin.doClick();  // Pressing Enter now works!
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    // Step 1: Ask for employee number
    String empNum = JOptionPane.showInputDialog(this, "Enter your employee number:");

    if (empNum == null || empNum.trim().isEmpty()) {
        return; // Cancelled or empty
    }

    empNum = empNum.trim();

    // Step 2: Check if employee exists in the system
    if (!securityAnswers.containsKey(empNum)) {
        JOptionPane.showMessageDialog(this, "Employee number not found.");
        return;
    }

    // Step 3: Ask for security question answer
    String answer = JOptionPane.showInputDialog(this, "What is your favorite animal?");
    if (answer == null || answer.trim().isEmpty()) {
        return; // Cancelled or empty
    }

    String storedAnswer = securityAnswers.get(empNum);

    if (!storedAnswer.equalsIgnoreCase(answer.trim())) {
        JOptionPane.showMessageDialog(this, "Incorrect answer to the security question.");
        return;
    }

    // Step 4: Let user enter new password
    String newPassword = JOptionPane.showInputDialog(this, "Enter your new password:");
    if (newPassword == null || newPassword.trim().isEmpty()) {
        return;
    }

    // Step 5: Update password in memory
    String username = usernameByEmpNum.get(empNum);
    userCredentials.put(username, newPassword);
    userPasswordByEmpNum.put(empNum, newPassword);

    // (Optional) Save new password to CSV here, if needed

    JOptionPane.showMessageDialog(this, "Password successfully reset. You may now log in.");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private String getFullNameFromUsername(String username) {
        return userFullNames.getOrDefault(username, "Unknown User");
   
}

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
new LoginScreen1().setVisible(true);
// Highlight 2: Removed duplicate setLocationRelativeTo(null) as it's now in the constructor.
// login.setLocationRelativeTo(null); // This line was a duplicate and is now handled in the constructor.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelLogin2;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JLabel loginLogo;
    private javax.swing.JLabel textLogo;
    // End of variables declaration//GEN-END:variables


