/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jas singh
 */
import java.text.SimpleDateFormat; // For formatting dates into strings.
import java.util.Date;             // Represents a specific instant in time.
import javax.swing.JOptionPane;    // Provides standard dialog boxes for user interaction.
import java.time.LocalDate;        // Modern Java API for handling dates.

/**
 * The `MainMenu` class represents the main application window.
 * It's a `JFrame` that provides navigation to other parts of the system,
 * such as Employee Table, Payslip generation, and Attendance tracking.
 */
public class MainMenu extends javax.swing.JFrame {
      private String fullName;
    
     // Member variables to hold instances of other GUI forms.
    // These forms are instantiated once and can be shown/hidden as needed.
    
    EmployeeTable femptable = new EmployeeTable(); // Instance of the Employee Table window.
    Payslip fpayslip = new Payslip();             // Instance of the Payslip generation window.
    Attendance fattendance = new Attendance();     // Instance of the Attendance tracking window.
// Instance of the Attendance tracking window.
// Instance of the Attendance tracking window.
// Instance of the Attendance tracking window.

    /**
     * Constructor for `MainMenu`.
     * Initializes the visual components of the main menu window.
     */
    public MainMenu(String fullName, String password) {
        this.fullName = fullName;
        initComponents();
        jLabelTitle2.setText("Welcome, " + fullName);
    }



 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle2 = new javax.swing.JLabel();
        jButtonTimein = new javax.swing.JButton();
        jButtonTimeout = new javax.swing.JButton();
        headerLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonEmployee = new javax.swing.JButton();
        jButtonPayslip = new javax.swing.JButton();
        jButtonAttendance = new javax.swing.JButton();
        jButtonExit2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTitle2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitle2.setFont(new java.awt.Font("Kinetika Bold", 1, 36)); // NOI18N
        jLabelTitle2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle2.setText("Welcome, Manuel Garcia III");
        jLabelTitle2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jButtonTimein.setBackground(new java.awt.Color(0, 51, 204));
        jButtonTimein.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonTimein.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimein.setText("Time IN");
        jButtonTimein.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonTimein.setPreferredSize(new java.awt.Dimension(83, 25));
        jButtonTimein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimeinActionPerformed(evt);
            }
        });

        jButtonTimeout.setBackground(new java.awt.Color(0, 51, 204));
        jButtonTimeout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonTimeout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimeout.setText("Time OUT");
        jButtonTimeout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonTimeout.setPreferredSize(new java.awt.Dimension(80, 25));
        jButtonTimeout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimeoutActionPerformed(evt);
            }
        });

        headerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoHeader.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelTitle2)
                .addGap(240, 240, 240)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(headerLogo))
                    .addComponent(jButtonTimein, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButtonTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerLogo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTimein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTitle2)
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));

        jButtonEmployee.setBackground(new java.awt.Color(14, 49, 113));
        jButtonEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmployee.setText("Employee Information");
        jButtonEmployee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeActionPerformed(evt);
            }
        });

        jButtonPayslip.setBackground(new java.awt.Color(14, 49, 113));
        jButtonPayslip.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPayslip.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPayslip.setText("Payslip");
        jButtonPayslip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayslipActionPerformed(evt);
            }
        });

        jButtonAttendance.setBackground(new java.awt.Color(14, 49, 113));
        jButtonAttendance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAttendance.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAttendance.setText("Attendance");
        jButtonAttendance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttendanceActionPerformed(evt);
            }
        });

        jButtonExit2.setBackground(new java.awt.Color(153, 0, 0));
        jButtonExit2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit2.setText("Sign Out");
        jButtonExit2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jButtonPayslip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(869, 869, 869)
                        .addComponent(jButtonExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButtonEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButtonPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButtonAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTimeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimeinActionPerformed
        // TODO add your handling code here:
        
        //get current date and time 
        Date now = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    String timeIn = sdf.format(now);
    
    // Display in a dialog or label
    JOptionPane.showMessageDialog(this, "Time In Recorded: " + timeIn);
        
    }//GEN-LAST:event_jButtonTimeinActionPerformed

    private void jButtonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeActionPerformed
        // TODO add your handling code here:
        femptable.show();
        
    }//GEN-LAST:event_jButtonEmployeeActionPerformed

    private void jButtonPayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayslipActionPerformed
    String input = JOptionPane.showInputDialog(
        this,
        "Enter Employee Number:",
        "Generate Payslip",
        JOptionPane.QUESTION_MESSAGE
    );

    if (input != null && !input.trim().isEmpty()) {


        // 🔽 Directly pass the Employee ID to Payslip
        new Payslip(input).setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Employee Number is required.", "Input Error", JOptionPane.WARNING_MESSAGE);
    }

    }//GEN-LAST:event_jButtonPayslipActionPerformed

    private void jButtonExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit2ActionPerformed
        // TODO add your handling code here:
        dispose ();
    }//GEN-LAST:event_jButtonExit2ActionPerformed

    private void jButtonTimeoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimeoutActionPerformed
        // TODO add your handling code here:
        Date now = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    String timeOut = sdf.format(now);
    
    // Display in a dialog or label
    JOptionPane.showMessageDialog(this, "Time Out Recorded: " + timeOut);
    }//GEN-LAST:event_jButtonTimeoutActionPerformed

    private void jButtonAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttendanceActionPerformed
        String input = JOptionPane.showInputDialog(
        this,
        "Enter Employee Number:",
        "Show Attendance",
        JOptionPane.QUESTION_MESSAGE
    );

    if (input != null && !input.trim().isEmpty()) {

        // Launch Attendance window
        Attendance attendanceWindow = new Attendance(input);  // Make sure Attendance has this constructor
        attendanceWindow.setVisible(true);

        // Optional: dispose current frame if needed
        // this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Employee Number is required.", "Input Error", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_jButtonAttendanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu("Default User", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerLogo;
    private javax.swing.JButton jButtonAttendance;
    private javax.swing.JButton jButtonEmployee;
    private javax.swing.JButton jButtonExit2;
    private javax.swing.JButton jButtonPayslip;
    private javax.swing.JButton jButtonTimein;
    private javax.swing.JButton jButtonTimeout;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
