import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.FileOutputStream;
import javax.imageio.ImageIO;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.File;
import javax.swing.JFileChooser;
import java.util.List;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author singh
 */

public class Payslip extends javax.swing.JFrame {
    private String empNo;
    public Payslip(String empNo) {
        this.empNo = empNo;
        initComponents();
        loadEmployeePayslip(empNo);
    }

    //  This allows creating Payslip with no parameters
    public Payslip() {
        initComponents();
    }
    
    private String getMonthYearString(int month, int year) {
    String[] monthNames = {"January", "February", "March", "April", "May", "June",
                           "July", "August", "September", "October", "November", "December"};
    return monthNames[month - 1] + " " + year;  // ✅ Ensures output like "June 2025"
}


    private void loadEmployeePayslip(String empNo) {

    // Retrieve Employee Details from File/Database
    Employee e = EmployeeFileHandler.getEmployee(Integer.parseInt(empNo)).orElse(null);

    if (e != null) {
        employeeNameLabel.setText(e.getFirstName() + " " + e.getLastName());
        employeeNumber.setText(empNo);
        position.setText(e.getPosition());
        employmentStatus.setText(e.getStatus());
        sssNumber.setText(e.getSssNumber());
        tinNumber.setText(e.getTinNumber());
        philhealthNumber.setText(e.getPhilHealthNumber());
        pagIbigNumber.setText(e.getPagIbigNumber());

        //  Set Allowance Fields
        double phone = e.getPhoneAllowance();
        double clothing = e.getClothingAllowance();
        double rice = e.getRiceSubsidy();

        phoneAllowance.setText(String.format("₱%,.2f", phone));
        clothingAllowance.setText(String.format("₱%,.2f", clothing));
        riceSubsidy.setText(String.format("₱%,.2f", rice));

        //  Set Hourly Rate (Restored)
        String cleanedRate = String.format("%.2f", e.getHourlyRate()).replaceAll("[^0-9.]", "");
        hourlyRate.setText(cleanedRate);

        //  Compute Total Benefits
        double totalBenefits = phone + clothing + rice;
        benefitsLabel.setText(String.format("₱%,.2f", totalBenefits));
    } else {
        JOptionPane.showMessageDialog(this, "Employee not found!", "Lookup Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        hoursWorked = new javax.swing.JLabel();
        overtime = new javax.swing.JLabel();
        hourlyRate = new javax.swing.JLabel();
        phoneAllowance = new javax.swing.JLabel();
        clothingAllowance = new javax.swing.JLabel();
        riceSubsidy = new javax.swing.JLabel();
        sssPremiumLabel = new javax.swing.JLabel();
        philhealthContributionLabel = new javax.swing.JLabel();
        pagibigContributionLabel = new javax.swing.JLabel();
        witholdingTaxLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        grossIncomeLabel = new javax.swing.JLabel();
        benefitsLabel = new javax.swing.JLabel();
        totalDeductionsLabel = new javax.swing.JLabel();
        otherAdjustments = new javax.swing.JLabel();
        netPayLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        employeeNumber = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        employmentStatus = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        sssNumber = new javax.swing.JLabel();
        tinNumber = new javax.swing.JLabel();
        philhealthNumber = new javax.swing.JLabel();
        pagIbigNumber = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        employeeNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        payDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        downloadButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        monthSelect = new com.toedter.calendar.JMonthChooser();
        yearSelect = new com.toedter.calendar.JYearChooser();
        checkPayslipButton = new javax.swing.JButton();
        payDateLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(880, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel20.setText("Hours Worked");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel21.setText("Salary Details");

        jLabel22.setText("Hourly Rate");

        jLabel23.setText("Clothing Allowance");

        jLabel24.setText("Phone Allowance");

        jLabel25.setText("Rice Allowance");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel26.setText("Benefits");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel27.setText("Deductions");

        jLabel28.setText("SSS Premium");

        jLabel29.setText("PhilHealth");

        jLabel30.setText("Pag-Ibig");

        jLabel31.setText("Withholding Tax");

        jLabel32.setText("Overtime");

        hoursWorked.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hoursWorked.setText("0");

        overtime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        overtime.setText("0");

        hourlyRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hourlyRate.setText("0");

        phoneAllowance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phoneAllowance.setText("0");

        clothingAllowance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clothingAllowance.setText("0");

        riceSubsidy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        riceSubsidy.setText("0");

        sssPremiumLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sssPremiumLabel.setText("0");

        philhealthContributionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        philhealthContributionLabel.setText("0");

        pagibigContributionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pagibigContributionLabel.setText("0");

        witholdingTaxLabel.setForeground(new java.awt.Color(153, 0, 0));
        witholdingTaxLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        witholdingTaxLabel.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(riceSubsidy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(clothingAllowance, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                            .addComponent(phoneAllowance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(overtime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hourlyRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hoursWorked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel21)
                            .addComponent(jLabel27))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(18, 18, 18)
                                .addComponent(witholdingTaxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pagibigContributionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(philhealthContributionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sssPremiumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursWorked))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(hourlyRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(overtime))
                .addGap(12, 12, 12)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(phoneAllowance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(clothingAllowance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(riceSubsidy))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(sssPremiumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(philhealthContributionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(pagibigContributionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(witholdingTaxLabel))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setText("Benefits");

        jLabel11.setText("Gross Income");

        jLabel12.setText("Deductions");

        jLabel13.setText("Other Adjustment");

        grossIncomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grossIncomeLabel.setText("0");

        benefitsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        benefitsLabel.setText("0");

        totalDeductionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalDeductionsLabel.setText("0");

        otherAdjustments.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        otherAdjustments.setText("0");

        netPayLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        netPayLabel.setForeground(new java.awt.Color(51, 102, 0));
        netPayLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        netPayLabel.setText("0");

        jLabel19.setText("Net Pay");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grossIncomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otherAdjustments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 4, Short.MAX_VALUE)
                                .addComponent(benefitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(totalDeductionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(netPayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossIncomeLabel)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(benefitsLabel))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(totalDeductionsLabel))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(otherAdjustments))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(netPayLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setText("Employee ID");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 26, -1, 20));

        jLabel44.setText("Employee Position");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel45.setText("Status");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel46.setText("SSS Number");
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 109, -1, -1));

        jLabel47.setText("TIN Number");
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 131, -1, -1));

        jLabel48.setText("Philheath Number");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel49.setText("Pag-Ibig Number");
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        employeeNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        employeeNumber.setText("10001");
        jPanel3.add(employeeNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 150, -1));

        position.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        position.setText("CEO");
        jPanel3.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 50, 140, -1));

        employmentStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        employmentStatus.setText("Regular");
        jPanel3.add(employmentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 70, 150, -1));

        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 181, 90, -1));

        sssNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sssNumber.setText("jLabel2");
        jPanel3.add(sssNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 110, 130, -1));

        tinNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tinNumber.setText("jLabel2");
        jPanel3.add(tinNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 130, 130, -1));

        philhealthNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        philhealthNumber.setText("jLabel2");
        jPanel3.add(philhealthNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 150, 130, -1));

        pagIbigNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pagIbigNumber.setText("jLabel5");
        jPanel3.add(pagIbigNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 170, 130, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("For Paydate:");

        employeeNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeNameLabel.setForeground(new java.awt.Color(0, 51, 102));
        employeeNameLabel.setText("Garcia, Manuel III");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("ELECTRONIC PAYSLIP OF:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Cutoff:");

        jLabel7.setText("SUMMARY:");

        jLabel8.setText("EMPLOYEE DETAILS:");

        jLabel9.setText("DETAILS:");

        downloadButton.setBackground(new java.awt.Color(14, 49, 113));
        downloadButton.setForeground(new java.awt.Color(255, 255, 255));
        downloadButton.setText("Download");
        downloadButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(153, 0, 0));
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        checkPayslipButton.setBackground(new java.awt.Color(14, 49, 113));
        checkPayslipButton.setForeground(new java.awt.Color(255, 255, 255));
        checkPayslipButton.setText("Check Payslip");
        checkPayslipButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkPayslipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPayslipButtonActionPerformed(evt);
            }
        });

        payDateLabel.setText("SELECT CUTOFF");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("CP2 H1102 SY24-25 Team Petix - C.Oreta, S.Singh, R.Sisles, J.Singh, D.Sumatra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel4)
                            .addGap(24, 24, 24)
                            .addComponent(monthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yearSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(checkPayslipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(employeeNameLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(127, 127, 127)
                                            .addComponent(payDate))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(payDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(555, 555, 555)
                                    .addComponent(downloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(employeeNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(payDateLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(payDate))
                    .addComponent(downloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(yearSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)))
                    .addComponent(checkPayslipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
               
    }//GEN-LAST:event_exitButtonActionPerformed

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
       try {
        //  Check if Employee ID exists
        if (empNo == null || empNo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Employee ID is missing!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //  Define Payslip Name (Example: "Payslip_10001_July_2024.pdf")
        String selectedMonthYear = getMonthYearString(monthSelect.getMonth() + 1, yearSelect.getYear());
        String fileName = String.format("Payslip_%s_%s.pdf", empNo, selectedMonthYear);

        //  Open File Chooser Dialog with Default File Name
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose Save Location");
        fileChooser.setSelectedFile(new File(fileName)); // Sets default filename
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection != JFileChooser.APPROVE_OPTION) {
            return; // Exit if user cancels
        }

        File saveFile = fileChooser.getSelectedFile(); // ✅ Get chosen file path

        //  Capture Screenshot of JFrame
        BufferedImage screenshot = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics2D g = screenshot.createGraphics();
        paint(g); // Render JFrame into image
        g.dispose();

        //  Save Screenshot as Temporary PNG
        File tempImage = new File("payslip_temp.png");
        ImageIO.write(screenshot, "png", tempImage);

        //  Create PDF Document
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(saveFile));
        document.open();

        //  Add Screenshot to PDF
        com.itextpdf.text.Image image = com.itextpdf.text.Image.getInstance("payslip_temp.png");
        image.scaleToFit(PageSize.A4.getWidth() - 40, PageSize.A4.getHeight() - 40); // Adjust size to fit page
        document.add(image);

        document.close();
        JOptionPane.showMessageDialog(this, "Payslip PDF saved successfully to:\n" + saveFile.getAbsolutePath(), 
            "Download Complete", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error saving PDF: " + e.getMessage(), "Download Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_downloadButtonActionPerformed

    private void checkPayslipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPayslipButtonActionPerformed

    if (empNo == null || empNo.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Employee ID is missing!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get month and year from UI controls
    int selectedMonth = monthSelect.getMonth() + 1; // JMonthChooser is 0-based (Jan=0)
    int selectedYear = yearSelect.getYear();

    try {
        // Fetch worked hours & overtime using AttendanceCalculator
        List<AttendanceRecord> allRecords = AttendanceFileHandler.readAllAttendanceRecords();
        double[] hours = AttendanceCalculator.computeMonthlyHoursAndOT(
                allRecords,
                Integer.parseInt(empNo),
                selectedMonth,
                selectedYear
        );

        // Ensure hourlyRate is cleaned before parsing
        String cleanedRate = hourlyRate.getText().replaceAll("[^0-9.]", "");
        double hourlyRateValue = Double.parseDouble(cleanedRate);

        // Compute gross income: (hoursWorked × hourlyRate) + overtimePay
        double overtimePay = SalaryComputation.computeOvertimePay(hours[1], hourlyRateValue);
        double grossIncome = SalaryComputation.computeGrossIncome(hours[0], overtimePay, hourlyRateValue);

        // Fetch Government Contributions from SalaryComputation
        double sssPremium = SalaryComputation.getSSSPremium(grossIncome);
        double philHealthPremium = SalaryComputation.getPhilHealthPremium(grossIncome);
        double pagIbigPremium = SalaryComputation.getPagIbigPremium(grossIncome);
        double withholdingTax = SalaryComputation.computeWithholdingTax(
                grossIncome - (sssPremium + philHealthPremium + pagIbigPremium));

        // Compute Total Benefits
        double totalBenefits = Double.parseDouble(benefitsLabel.getText().replaceAll("[^0-9.]", ""));

        // Compute Total Deductions
        double totalDeductions = sssPremium + philHealthPremium + pagIbigPremium + withholdingTax;

        // Compute Net Pay
        double netPay = grossIncome + totalBenefits - totalDeductions;

        // Compute Pay Date (Next Month's 15th)
        LocalDate payDate = LocalDate.of(selectedYear, selectedMonth, 1)
                                     .plusMonths(1)
                                     .withDayOfMonth(15);
        String formattedPayDate = payDate.format(DateTimeFormatter.ofPattern("MMMM dd, yyyy"));

        // Update Payslip Fields
        hoursWorked.setText(String.format("%.2f", hours[0]));
        overtime.setText(String.format("₱%,.2f", overtimePay)); // OT at 1.5x
        grossIncomeLabel.setText(String.format("₱%,.2f", grossIncome));

        // Display Government Contributions
        sssPremiumLabel.setText(String.format("₱%,.2f", sssPremium));
        philhealthContributionLabel.setText(String.format("₱%,.2f", philHealthPremium));
        pagibigContributionLabel.setText(String.format("₱%,.2f", pagIbigPremium));
        witholdingTaxLabel.setText(String.format("₱%,.2f", withholdingTax));
        totalDeductionsLabel.setText(String.format("₱%,.2f", totalDeductions));

        // Display Net Pay
        netPayLabel.setText(String.format("₱%,.2f", netPay));

        // Display Pay Date
        payDateLabel.setText(formattedPayDate);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Error computing payslip: " + e.getMessage(),
                "Computation Error",
                JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_checkPayslipButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel benefitsLabel;
    private javax.swing.JButton checkPayslipButton;
    private javax.swing.JLabel clothingAllowance;
    private javax.swing.JButton downloadButton;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JLabel employeeNumber;
    private javax.swing.JLabel employmentStatus;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel grossIncomeLabel;
    private javax.swing.JLabel hourlyRate;
    private javax.swing.JLabel hoursWorked;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.toedter.calendar.JMonthChooser monthSelect;
    private javax.swing.JLabel netPayLabel;
    private javax.swing.JLabel otherAdjustments;
    private javax.swing.JLabel overtime;
    private javax.swing.JLabel pagIbigNumber;
    private javax.swing.JLabel pagibigContributionLabel;
    private javax.swing.JLabel payDate;
    private javax.swing.JLabel payDateLabel;
    private javax.swing.JLabel philhealthContributionLabel;
    private javax.swing.JLabel philhealthNumber;
    private javax.swing.JLabel phoneAllowance;
    private javax.swing.JLabel position;
    private javax.swing.JLabel riceSubsidy;
    private javax.swing.JLabel sssNumber;
    private javax.swing.JLabel sssPremiumLabel;
    private javax.swing.JLabel tinNumber;
    private javax.swing.JLabel totalDeductionsLabel;
    private javax.swing.JLabel witholdingTaxLabel;
    private com.toedter.calendar.JYearChooser yearSelect;
    // End of variables declaration//GEN-END:variables
}
